### ISSUE TITLE
Uploading a jpeg doesnt always work

### ISSUE THREAD

**Issue by galaxyxtwo** [galaxyxone/openlinks#111]
Make sure jpeg uploads work

**Comment by noryev** [comment]
Can you possibly outline this a little better? What browser are you using? How large is the jpeg you're uploading?

**Comment by galaxyxtwo** [comment]
Definitely. After looking into this further it appears the file size is the issue. 
- 5.3 mb jpeg in brave did not work
- 3.4 mb jpeg in chrome did not work

- 258 KB jpeg in brave worked
- 197 KB jpeg in brave worked
- 29 KB jpeg in chrome worked

**Comment by noryev** [comment]
As @m-yasir pointed out to me, this is a hard limitation with the Lambda server. Use images smaller than 3mb I believe.
